SELECT DRLFL.CORP_ID, DRLFL.FILE_YEAR, 
       DRLFL.ADJUST_ID AS "FL_ADJ_ID", DECODE(DRLFL.ADJUST_CODE, 'FL', '1st Letter') AS "FL_ADJ_CODE", 
          DRLFL.UPD_ID AS "FL_UPD_ID", TO_CHAR(DRLFL.UPD_DATE, 'MM/DD/YYYY') AS "FL_UPD_DATE",
       DRLSL.ADJUST_ID AS "SL_ADJ_ID", DECODE(DRLSL.ADJUST_CODE, 'SL', '2nd Letter') AS "SL_ADJ_CODE", 
          DRLSL.UPD_ID AS "SL_UPD_ID", TO_CHAR(DRLSL.UPD_DATE, 'MM/DD/YYYY') AS "SL_UPD_DATE",
       DRLFC.ADJUST_ID AS "FC_ADJ_ID", DECODE(DRLFC.ADJUST_CODE, 'FC', '1st Call') AS "FC_ADJ_CODE", 
          DRLFC.UPD_ID AS "FC_UPD_ID", TO_CHAR(CLDFC.UPD_DATE, 'MM/DD/YYYY') AS "FC_UPD_DATE", CLDFC.COMMENTS AS "FC_COMMENTS",
       DRLSC.ADJUST_ID AS "SC_ADJ_ID", DECODE(DRLSC.ADJUST_CODE, 'SC', '2nd Call') AS "SC_ADJ_CODE", 
          DRLSC.UPD_ID AS "SC_UPD_ID", TO_CHAR(CLDSC.UPD_DATE, 'MM/DD/YYYY') AS "SC_UPD_DATE", CLDSC.COMMENTS AS "SC_COMMENTS"                  

FROM (SELECT DISTINCT CORP_ID, ADJUST_ID, ADJUST_CODE, FILE_TYPE, UPD_ID, UPD_DATE, FILE_YEAR
                FROM TBL1.SUBTBL2
                WHERE 1=1
                    AND FILE_TYPE = 1
                    AND FILE_YEAR > 2015
                    AND ADJUST_CODE = 'FL') DRLFL

LEFT JOIN (SELECT DISTINCT CORP_ID, ADJUST_ID, ADJUST_CODE, FILE_TYPE, UPD_ID, UPD_DATE, FILE_YEAR
                FROM TBL1.SUBTBL2
                WHERE 1=1
                    AND FILE_TYPE = 1
                    AND FILE_YEAR > 2015
                    AND ADJUST_CODE = 'SL') DRLSL
          ON DRLFL.CORP_ID = DRLSL.CORP_ID
          
LEFT JOIN (SELECT DISTINCT CORP_ID, ADJUST_ID, ADJUST_CODE, FILE_TYPE, UPD_ID, UPD_DATE, FILE_YEAR
                FROM TBL1.SUBTBL2
                WHERE 1=1
                    AND FILE_TYPE = 1
                    AND FILE_YEAR > 2015
                    AND ADJUST_CODE = 'FC') DRLFC
          ON DRLFL.CORP_ID = DRLFC.CORP_ID
LEFT JOIN (SELECT DISTINCT ADJUST_ID, COMMENTS, UPD_DATE
                FROM TBL1.SUBTBL1) CLDFC
          ON DRLFC.ADJUST_ID = CLDFC.ADJUST_ID
          
LEFT JOIN (SELECT DISTINCT CORP_ID, ADJUST_ID, ADJUST_CODE, FILE_TYPE, UPD_ID, UPD_DATE, FILE_YEAR
                FROM TBL1.SUBTBL2
                WHERE 1=1
                    AND FILE_TYPE = 1
                    AND FILE_YEAR > 2015
                    AND ADJUST_CODE = 'SC') DRLSC
          ON DRLFL.CORP_ID = DRLSC.CORP_ID
LEFT JOIN (SELECT DISTINCT ADJUST_ID, COMMENTS, UPD_DATE
                FROM TBL1.SUBTBL1) CLDSC
          ON DRLSC.ADJUST_ID = CLDSC.ADJUST_ID
                              
ORDER BY 
    GREATEST(NVL(DRLFL.UPD_DATE, SYSDATE-10000), NVL(DRLSL.UPD_DATE, SYSDATE-10000), NVL(DRLFC.UPD_DATE, SYSDATE-10000), NVL(DRLSC.UPD_DATE, SYSDATE-10000))
    DESC
;